Starts game engine
Rolf1e/rts-m2-rust pull request #2
Opened 2022-02-04 11:19 UTC by Rolf1e

Add structures
- [x] Unit
- [x] Skill
- [ ] Building
- [ ] Player

Some uts and exceptions

2022-02-07 07:06 UTC, cafehaine requested changes
2 small nits, looks good to me otherwise!

2022-02-07 07:06 UTC, cafehaine commented on rts-core/src/components/playground.rs
> +pub struct PlayGround {
I guess this means that only two players are supported in a game?
Do you think it'll be easy to switch to an arbitrary number of players in the future?

2022-02-07 07:06 UTC, cafehaine commented on rts-core/src/entity/unit.rs
> +                "Failed to update mana",
Failed to update health?

2022-02-07 18:54 UTC, Rolf1e commented on rts-core/src/components/playground.rs
> +pub struct PlayGround {
I will update with a Vec<Player> you're right !

2022-02-08 18:23 UTC, cafehaine approved these changes
Looks good to me!

2022-02-08 19:33 UTC, merged